name: Deploy to Yandex Cloud Serverless Container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: cr.yandex
  IMAGE_NAME: capital-compass

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: json_key
          password: ${{ secrets.YC_SA_JSON }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.YC_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Yandex Cloud Serverless Container
        if: github.ref == 'refs/heads/main'
        run: |
          # Установка Yandex CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin

          # Аутентификация с помощью service account
          echo '${{ secrets.YC_SA_JSON }}' > sa.json
          yc config set service-account-key sa.json

          # Настройка yc
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

          # Проверка сервисного аккаунта
          echo "Checking service account: ${{ fromJson(secrets.YC_SA_JSON).service_account_id }}"
          yc iam service-account get ${{ fromJson(secrets.YC_SA_JSON).service_account_id }} || echo "Service account not found or no access"

          # Обновление ревизии контейнера (контейнер должен быть создан заранее)
          yc serverless container revision deploy \
            --container-name ${{ secrets.YC_CONTAINER_NAME }} \
            --image ${{ env.REGISTRY }}/${{ secrets.YC_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest \
            --service-account-id ${{ fromJson(secrets.YC_SA_JSON).service_account_id }} \
            --environment "BOT_MODE=webhook,WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }},PUBLIC_BASE_URL=,LOG_LEVEL=info,API_TIMEOUT_MS=7000,TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},YC_API_KEY=${{ secrets.YC_API_KEY }},YC_FOLDER_ID=${{ secrets.YC_FOLDER_ID }},YC_GPT_MODEL=${{ secrets.YC_GPT_MODEL }},YC_GPT_ENDPOINT=${{ secrets.YC_GPT_ENDPOINT }}" \
            --memory 512m \
            --cores 1 \
            --execution-timeout 30s \
            --concurrency 1

      - name: Cleanup
        if: always()
        run: |
          rm -f sa.json
